### ISSUE TITLE
[Feature]: allow SPA deletion by users who didn't create the SPA

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#1107]
## Is your feature request related to a problem? Please describe:

Currently, the `DELETE /api/v1/applications/:name` request can only succeed if the user running it is the same user who created the SPA.  If you didn't create the SPA, you can't delete it.

## Describe the solution you'd like:

Allow any authenticated user to delete SPAs.

**Comment by sayak-sarkar** [comment]
Interesting! @mwcz should these be authenticated users who are added to the spaship_users rover group?

**Comment by mwcz** [comment]
They already must be in that group to log into SPAship, and to create API keys, no?
