### ISSUE TITLE
[Chore]: Update ubi-minimal version in spaship/httpd

### ISSUE THREAD

**Issue by lkrzyzanek** [spaship/spaship#1193]
## Is your chore related to a problem? Please describe:
spaship-httpd 0.1.0 has high vulnerabilities:
https://quay.io/repository/spaship/httpd/manifest/sha256:097038c952427a4e6a34e9d1b492bb09c75c9e458be514c9517f48ade458b229?tab=vulnerabilities
resp. 
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.3-291&push_date=1613553653000

## Describe the solution you'd like:

Upgrade the ubi-minimal to version 8.3-298.1618432845
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.3-298.1618432845&push_date=1618946153000&container-tabs=overview

and deploy it under another tag e.g. 0.2.0 or use 1.3.0 notation to be in sync with major.minor version of spaship operator

**Comment by kunyan** [comment]
https://github.com/spaship/httpd/commit/5ca8c577d7d1313ff1eadcdf66aea2805cd74236

Done

**Comment by lkrzyzanek** [comment]
@kunyan Thanks a lot. Could you please create a git tag so we'll also get the tagged images not only `latest`? Operator's version is now 1.3.5 so having spaship/httpd with tag `1.3.5` would makes perfect sense as well.
