### ISSUE TITLE
init.html should not in root directory

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#140]
Now. the `init.html` is not in scm.

I suggest we should put it into OpenShift configMap. then it could be mount into the Pod.
But if you want to mount it to some path, the content of path will be overwrite. that's is why I suggest `init.html` not put into root path of SPA directory.

I think we could put it into `/_include_/init.html`.
The `chrome` snippets could also put into `/_chrome_/`.
It should not be able to read by path proxy or sync-service list api

**Comment by mwcz** [comment]
I agree, :+1:

**Comment by sayak-sarkar** [comment]
@kunyan is this issue still valid or was it already fixed in #241

**Comment by kunyan** [comment]
All include snippets will be store in `/var/www/html/.include`. I'll change config in OpenShift to make it work.

We should show people how to use SSI in their `index.html`

**Comment by kunyan** [comment]
I added usage in FAQ [How to integrate Red Hat Customer Portal chrome framework?](/spaship/spaship/wiki/FAQ#1-how-to-integrate-red-hat-customer-portal-chrome-framework)
