### ISSUE TITLE
(JS-0093) Avoid having unused expressions

### ISSUE THREAD

**Issue by sayak-sarkar** [spaship/spaship#1412]
## Description
An unused expression that does not affect the state of the program indicates a logic error.

## Occurrences
There are 7 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/spaship/spaship/issue/JS-0093/occurrences/](https://deepsource.io/gh/spaship/spaship/issue/JS-0093/occurrences/)

**Comment by luko0610** [comment]
@sayak-sarkar Can I work on this? As far as I understand simply replace those occurences with an if statement would solve the issue.
