### ISSUE TITLE
Write documentation on how to use an API key in cli, curl, etc

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#164]
We need to provide documentation for users on how to use their API keys.

- [x] document using an API key with the cli
- [x] document using an API key with curl

**Comment by nidhisharma000** [comment]
I'm a technical writer who is brand new to writing API documentation and I know Python and JavaScript, could I try documenting the cli, curl request?

**Comment by npatil9** [comment]
@sayak-sarkar would look into this later this week, most probably by Thursday, 19th Mar.

**Comment by mwcz** [comment]
Part of this is done since I added api key support to the CLI, including documentation in the README.  The cURL documentation is a lot less important so I'd be okay with calling this done.

**Comment by sayak-sarkar** [comment]
Waiting on #282
