### ISSUE TITLE
Create REST endpoints for API keys

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#166]
This is related to #163

Create REST endpoints for creating, fetching and deleting API keys.  The functions implementing key creation and deletion already exist in `sync-service/lib/db.apikey.js`, they just need to be wired up to URL paths in express.

Here's my thoughts on endpoint paths and HTTP methods.

| HTTP method | path | result |
| --- | --- | --- |
| `POST` | `/apikey` | creates and returns an API key object such as `{ key: "ABCD" }` |
| `DELETE` | `/apikey?hashedKey=e12e115a` | Deletes key ABCD (hashed to "e12e115a") <sup>1</sup> <sup>2</sup> |
| `GET` | `/apikey?user=babyyoda` | Returns an API key object such as `{ user: "babyyoda", key: "ABCD" }` |
| `GET` | `/user?hashedKey=ABCD` | Returns an API key object such as `{ user: "babyyoda" }` |
| `DELETE` | `/user?user=babyyoda` | Deletes all API keys for user babyyoda

**Notes**
<sup>1</sup> The function `deleteKey(apikey)` function wants you to pass in the HASHED key, not the original key (since SPA manager does not have access to the original key when you click "Delete key").  That's why the querystring param is `hashedKey` and not `key`.
<sup>2</sup> This should return a JSON object describing whether the key creation was successful or not (key deleted successfully, or key not found).

**Comment by npatil9** [comment]
This issue is a blocker for @kunyan. Can you update the latest status?
