### ISSUE TITLE
[Bug]: Manager styling issues

### ISSUE THREAD

**Issue by sayak-sarkar** [spaship/spaship#1673]
## Describe the bug:
Here's a list of styling issues with screenshots attached:

1. Sign In with SSO button section position: <img width="886" alt="image" src="https://user-images.githubusercontent.com/1418735/165310190-7686b11b-d53b-4fe8-9b32-419fcd4d06f3.png">

2. Media Queries Needed: ![image](https://user-images.githubusercontent.com/1418735/165312648-ce418c17-94fa-4165-acb9-cfa3560fc94c.png)

3. When backend API connection fails, Manager throws this fatal error. The Manager should fail gracefully: <img width="960" alt="image" src="https://user-images.githubusercontent.com/1418735/165312881-a503de80-c679-4d83-9806-8edc6c63b91c.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1418735/165313429-bca1c6e8-0bce-4429-8bbe-4e1e7ae6021c.png">

4. Activity Stream entries are incomplete such as ` hydraendpoint has been deployed for ecosystem-catalog on ` the end part is missing. <img width="1326" alt="image" src="https://user-images.githubusercontent.com/1418735/165314471-5e3275cb-772d-48aa-81f6-74b5bd38d958.png">

5. SPA list is getting randomized every time the page loads. The SPA list should be sorted by name: 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1418735/165315320-568ac359-edba-4aa1-9267-d23f1c888172.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1418735/165315369-35977dba-9dc6-459f-95b3-0987346567f4.png">

6. Media queries needed: 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/1418735/165316596-73efaf32-3545-4734-a14f-9474a71928c0.png">

7. Table columns and buttons need to be consistent 
![image](https://user-images.githubusercontent.com/1418735/165316731-d1de8d07-5ed2-4bf3-b571-7907066677c6.png)

## Steps to reproduce:
Visit each of the pages in different resolutions and scroll through each page.

## Expected behavior:
All interactions should be seamless and consistent.

## Environment;

- Operating System(s): All
- Browser: All

**Comment by hybridx** [comment]
Remove web prop button
