### ISSUE TITLE
[Bug]: v1.5 breaks url settings in a spaship project's .spashiprc.yml

### ISSUE THREAD

**Issue by Djfaucette** [spaship/spaship#1811]
## Describe the bug:

After attempting to use the cli @ 1.5 I encounter this message anytime I attempt to deploy:
```Lost connections usually still result in successful deployments, and are caused by a simple network timeout during archive processing.  Please confirm your deployment succeeded by checking the SPAship UI, and checking your application in the environment you deployed to.```

## Steps to reproduce:
In any project with origin-only urls in the env object of a `.spashiprc.yml` file try the command `npx @spaship/cli@1.5 deploy ${YOUR_ARCHIVE}`. You should see the following message. @arkaprovob mentioned a workaround by adding `/applications/deploy` to the end of these urls. This works, but is a breaking change from `v0.14.0`. Adding a release that could leave these urls alone would be incredibly helpful, and prevent work across a dozen or so applications hosted on access via SPAship.

## Expected behavior:

Entering the above command could work with a origin-only url instead of an error message.

## Environment;
Any linux or unix machine via command line/cli.

**Comment by hybridx** [comment]
Hey @Djfaucette we have added a fix for this in #1813
