### ISSUE TITLE
[Chore]: Why use bash source for env when nextjs has prebuilt .env loading

### ISSUE THREAD

**Issue by akhilmhdh** [spaship/spaship#1852]
## Is your chore related to a problem?

Right now spaship manager, loads environment variable via bash scripts. There are multiple bash script implemented for this. 

Reference: https://github.com/spaship/spaship/tree/master/packages/manager/scripts

First of all this is a bit confusing to be honest on where to keep these and second which is the solution is nextjs hsa prebuilt support for this

## Describe the solution you'd like:

NextJS Environment Doc: https://nextjs.org/docs/basic-features/environment-variables

NextJS has support to load .env before server starts or builds.

You can load the env based on environemenets like development, test, prod

All you need to do is put a .env.local or .env.<environement> file in  manager root directory. 

This will remove all those bash script and keeps everything easy to setup. 

## Describe alternatives you've considered:

Nil

## Additional context:

Nil

**Comment by akhilmhdh** [comment]
Let me know if you the team want's to move to `.env` file convention. Ill be happy to contribute these changes.

**Comment by arkaprovob** [comment]
@akhilmhdh I have gone through the document link you shared. That's a lovely proposal. @hybridx @soumyadip007, what do you think?

**Comment by hybridx** [comment]
@akhilmhdh I think we can do this later as well, right now I think the README update and code structure updates would be more important.

**Comment by akhilmhdh** [comment]
Yah i know and we will get there. 

I had a discussion with @arkaprovob 

Let's go one step at a time, without breaking existing thing. Existing one has lot of issues. 
We cannot just put swr. It will take time.

**Comment by akhilmhdh** [comment]
Closing as this has been fixed with #1879
