### ISSUE TITLE
MongoDB config should not use only one string

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#202]
I know using following way to connect mongodb is easy for use

```mongodb://db1.example.net,db2.example.net:2500/?replicaSet=test&connectTimeoutMS=300000```

But we will use the MongoDB instance with authentication. it means there should be some secret inside
In the OpenShift, we always store them into single value

example:
- MONGODB_USER
- MONGODB_PASSWORD
- MONGODB_DATABASE

It is very difficult to put them together into one string with OpenShift secret mapping.
Please read each value from environments

**Comment by mwcz** [comment]
Great idea, I like it. :+1:

**Comment by mwcz** [comment]
This is complete now, right?

**Comment by kunyan** [comment]
#203 Fixed
