### ISSUE TITLE
test: API test

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#206]
- Add script for /deploy and /list

- Update the script with API key

Tools: newman

**Comment by tanyutu** [comment]
Add script for /deploy and /list is done .  wait for API key ready and update the script

**Comment by mwcz** [comment]
Great, thanks @tanyutu !  If the script for `/deploy` and `/list` is ready, can you go ahead and open a draft pull request?  You don't have to wait for the apikey API to be ready. :)

**Comment by tanyutu** [comment]
it's done and merged
