### ISSUE TITLE
test: E2E test

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#207]
E2E test for spa manager.

**Comment by tanyutu** [comment]
pending on UI work.

**Comment by tanyutu** [comment]
working on SSO login.

**Comment by tanyutu** [comment]
E2E test is perform with cypress.
Below tests are done on dev, need to wait for workflow ready to test.
1. Login is done
2. Logout is done
3. Application (new & search) is done
4. API key(generate & revoke ) is done
Need to be done:
1. wait for some elements id ready (linked with issue261)
2. application detail page is not ready.

**Comment by mwcz** [comment]
This is awesome!  Where can we see the test results and how can we run the tests?

**Comment by kunyan** [comment]
#46 is same issue

**Comment by tanyutu** [comment]
it's done.
