### ISSUE TITLE
Can we remove `handlebars` dependency ?

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#235]
There has a security vulnerabilities which is one of dependencies of `handlebars`.

I just check our files which use `handlebars`.
it is very easy to replaced by [Template literals (Template strings)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

```javascript
const templateString = `
Header set X-Spaship-Name "{{ name }}"


Replace this part
{{#if single }}
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.html
    Header set X-Spaship-Single "true"
</IfModule>
{{/if}}
`;
```

To

```javascript
let templateString = `Header set X-Spaship-Name ${name}`

if (single) {
  templateString += `
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.html
    Header set X-Spaship-Single "true"
</IfModule>
`
}
`;
```

I think the `common` should not have many 3rd dependencies which is not important. it should be small.

What do you think @mwcz  ?

**Comment by mwcz** [comment]
100% agree, this is a good change.
