### ISSUE TITLE
[security] spaship.yaml exposed to public

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#242]
example: 
https://spaship-router-cpops-dev.ext.us-west.dc.preprod.paas.redhat.com/kyan/test/spaship.yaml

A simple way to fix it
```
<FilesMatch "^spaship\.yaml">
        Require all denied
</FilesMatch>
```

But in long term. the deploy key should not exist in `spaship.yaml`, it will also exposed in git repo. the end user should store it in some secrets

I think the spaship.yaml should only have following fields
* name
* path
* single

The others like `ref`, it should be dynamic. `deployKey` should be a secret

**Comment by mwcz** [comment]
Agree.  `deploykey` isn't a security measure.  It is simply a tool to prevent accidental overwriting of SPAs.  It's also meant to be temporary and can be removed once we have a user & permissions database.

So in short I totally agree with the Apache config for hiding it (there's no reason it should be web accessible).  And I agree that deploykey should not exist in spaship.yaml long term.  But I also think that spaship.yaml itself should not exist long-term. :)

**Comment by kunyan** [comment]
I had apply this change to Dev env
