### ISSUE TITLE
spaship-manager- no error msg for duplicated label when create a new apikey

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#318]
## Describe the bug:
Tested on dev environment of Authentication page
Try to create a new apikey with duplicated label, the apikey can't be generated but no msg pop up. In addition, on the apikey list page, some part of the duplicated apikey info show .

- 

## Steps to reproduce:

- Login dev environment

- Click Create API Key

- Fill the label with a duplicated value and choose all environment 

- Click Create API Key. 

Actual: 

- No error msg pop up for duplicated label. 

- The information still show on list page

## Expected behavior:

error msg for duplicated label pop up
no information of duplicated record show in list page
## Environment;

dev environment

**Comment by npatil9** [comment]
We have been seeing this issue for quite some time and should be fixed for catalog onboarding.

**Comment by kunyan** [comment]
Will disable submit button if user typing a exist api label
