### ISSUE TITLE
Create E2E test for root path spa

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#358]
Now that the router can support spas deployed at the root we should create an E2E test for this.

Here are the requirements:
1.  A spa can be deployed through the API at `path=/`
2.  Then that spa can be accessed by hitting spaship at the root e.g. http://localhost:8080/
3. Other sub-path spas should continue to work even when a root path spa is deployed, so if a new spa is deployed at `path=/foo` then both http://localhost:8080/ and http://localhost:8080/foo should work

**Comment by tanyutu** [comment]
Wait for the new pr merged for function of deploy ready.

**Comment by tanyutu** [comment]
issue #364 blocks the e2e test.
