### ISSUE TITLE
[Bug]: root path spa will get redirect loop

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#364]
## Describe the bug:

When we access the router root path, it should return the root spa
However, it will add `//` in the end and redirect loop

## Expected behavior:

Root path SPA display

## Screenshots:

<img width="851" alt="Screen Shot 2020-04-20 at 7 03 27 PM" src="https://user-images.githubusercontent.com/752130/79744833-a9996b80-8339-11ea-9b90-f88192f64013.png">

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

**Comment by Jared-Sprague** [comment]
This is due to the changes in common flatpath.   I implemented the special logic outside of the common package in router, I think we should do the same for API, or re-implement the changes in router to based on the common package changes.

**Comment by Jared-Sprague** [comment]
Caused by #361

I think a small bit of logic in router should fix this.
