### ISSUE TITLE
[Bug]: Creating a new API Key results in empty Env labels

### ISSUE THREAD

**Issue by sayak-sarkar** [spaship/spaship#374]
## Describe the bug:
Creating a new API Key from the SPA Manager Page results in empty Environment labels under the Key List's Scope Column.

## Steps to reproduce:
1. Go to `/authentication/apikeys`.
2. Click `Create API Key`.
3. Add details and select all Envs.
4. Click `Create API key`.
5. Close modal.
6. Expand the new key entry.

Refreshing the page seems to fix this issue.

## Expected behavior:
Instead of blank pills under the Scope column, it should show individual env names.

## Screenshots:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1418735/79815920-94572800-839f-11ea-84c2-4a0c6dbf525e.png">

**Comment by kunyan** [comment]
Fixed in #372
