### ISSUE TITLE
[Bug]: The path in new application page is not correct, this bug will affect e2e test script.

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#375]
## Describe the bug:
The path in new application page is not correct

## Steps to reproduce:
1. login dev environment
2. click create new application
Actual:
The address in path is not correct 

## Expected behavior:
Please put the right link in the path.

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

**Comment by kunyan** [comment]
I updated config file, but another issue come #380 

You could force refresh `https://{manager}/config/manager.js` to fix this problem

**Comment by kunyan** [comment]
I'll close this issue
