### ISSUE TITLE
[Bug]: Sometimes UI hangs when deploying new application

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#392]
## Describe the bug:

When clicking submit to deploy a new application, sometimes the UI hangs and spins on the Submit button.  This happened when we were trying to re-deploy to an existing name and path.

## Steps to reproduce:

1. Deploy an application with a name and path
2. re-deploy it again at the same name and path
3. repeat until UI hangs on submit button

## Expected behavior:

UI should not hang on Submit

**Comment by kunyan** [comment]
I think the issue should be fixed.

BUT in sometime like bad networking. it will be chance to get an error.
The reason is the upload is timeout, and the current ajax method is `fetch`, not have a timeout option.
