### ISSUE TITLE
[Question]: deploy seems not support .tar.bz2

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#409]
## Steps to reproduce:
1. login spa manager UI
2. deploy a new application with attachment of .tar.bz2
ACTUAL
page always loading with no error pop up. but never works for the new application creation.

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

**Comment by kunyan** [comment]
[file.tar.bz2.txt](https://github.com/spaship/spaship/files/4537850/file.tar.bz2.txt)

**Comment by tanyutu** [comment]
[myfile.tar.bz2.txt](https://github.com/spaship/spaship/files/4537860/myfile.tar.bz2.txt)

**Comment by kunyan** [comment]
I tested bz2 file, we are support it
