### ISSUE TITLE
documentation to be part of SPAship product and not just repo. 

### ISSUE THREAD

**Issue by npatil9** [spaship/spaship#414]
Users should be able to view product documentation in the SPA manager.

**Comment by kunyan** [comment]
I was plan added [docusaurus](https://v2.docusaurus.io/) to do it

**Comment by sayak-sarkar** [comment]
@kunyan Nice! I am also planning to use docusaurus for this! :-)

**Comment by Jared-Sprague** [comment]
Acceptance critiera: Documentation link on the manager, that renders the docusaurus markdown

**Comment by sayak-sarkar** [comment]
Documentation on SPAship usage drafted at: https://docs.google.com/document/d/18UkX3KtiC-tqm381qARBm0DSWjK0aMbQxfBya94QQ0U/edit?skip_itp2_check=true#heading=h.g3tsvxdc2yr3

**Comment by npatil9** [comment]
We are going to open a separate issue for home page. Closing this one.
