### ISSUE TITLE
[api] add tests

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#45]
Unit tests:
- [x] lib/background/autosync.js
- [ ] lib/deploy.js (pending #47)
- [x] lib/metadata.js

Funcional tests:
- [ ] POST /deploy
- [ ] GET /list
- [ ] POST /autosync/forceSyncAll

**Comment by npatil9** [comment]
@sayak-sarkar can you take it?

**Comment by sayak-sarkar** [comment]
Yup!

**Comment by sayak-sarkar** [comment]
Waiting on #282

**Comment by kunyan** [comment]
#282 added controller level test

* [x] `GET` /applications
* [x] `POST` /applications
* [ ] `POST` /applications/deploy
* [x] `GET` /apiKeys
* [x] `POST` /apiKeys
* [x] `DELETE` /apiKeys

only `/application/deploy` not have test


The `autosync` been moved to own package `@spaship/sync`.

**Comment by sayak-sarkar** [comment]
@spaship/developers I'm a bit unsure about how to mock the deploy service in order to test the `POST` for /applications/deploy.
Any suggestions here?
