### ISSUE TITLE
add integration test scenarios at the monorepo root

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#46]
Test scenarios spanning the full usage spectrum, such as:
- [ ] launch sync-service & path-proxy, spaship init, spaship deploy, and make sure the deployed app resolves correctly
- [ ] others?

**Comment by Jared-Sprague** [comment]
Kun will get Wei into the github org and assign to her

**Comment by mwcz** [comment]
Daniel just introduced me to Cypress.  It looks like it could be an excellent e2e test framework for us.  I don't know the e2e offerings that well, but it is worth looking at. https://www.cypress.io/

**Comment by tanyutu** [comment]
Cypress is great E2E tool. But it doesn't support kerberos SSO login yet. Have to workaround with api to resolve this if using cypress.

**Comment by npatil9** [comment]
This is a part of #207 and should be covered.

**Comment by tanyutu** [comment]
it's done with #207
