### ISSUE TITLE
[Bug]: SSI is broken

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#462]
## Describe the bug:

SSI is broken

## Steps to reproduce:

1. Go to this app: https://spaship-router-cpops-dev.ext.us-west.dc.preprod.paas.redhat.com/demo/chrome/

SSI directives for chrome not working

## Expected behavior:

SSI for chrome should be working

## Screenshots:

![Screenshot from 2020-05-12 06-04-40](https://user-images.githubusercontent.com/3926730/81671034-7e74da00-9416-11ea-9f91-a2f8edfbdceb.png)

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

**Comment by kunyan** [comment]
There has a OpenShift mount conflict between `init.html` and `chrome`
So I moved `init.html` to `init/index.html`

```html
<!DOCTYPE html>
<html class="no-js nimbus">
   <head>
       <!--#include virtual="/.include/init/index.html" -->
       <!--#include virtual="/.include/chrome/head/$locale/head.html" -->
       <!-- put YOUR_HEAD_CONTENT here -->
   </head>
   <body>
      <!--#include virtual="/.include/chrome/header/$locale/header.html" -->
      <div class="YOUR_APP_NAME_CLASS">
          <!-- put YOUR_CONTENT_HERE -->
      </div>
      <!--#include virtual="/.include/chrome/footer/$locale/footer.html" -->
   </body>
</html>
```

[How to integrate Red Hat Customer Portal chrome framework?](/spaship/spaship/wiki/FAQ#1-how-to-integrate-red-hat-customer-portal-chrome-framework)

**Comment by kunyan** [comment]
I had fix the path issue manually

and a PR for fix test fixture https://github.com/spaship/spaship/pull/482
