### ISSUE TITLE
[Chore]: Hardcoded OpenAPI server details should be replaced by Environment Variables.

### ISSUE THREAD

**Issue by sayak-sarkar** [spaship/spaship#474]
## Is your chore related to a problem? Please describe:
API server details are currently hardcoded into OpenAPI configuration.

## Describe the solution you'd like:
OpenAPI config should be populated from Environment Variables

**Comment by kunyan** [comment]
Bingo : 
https://github.com/scottie1984/swagger-ui-express#modify-swagger-file-on-the-fly-before-load

We can show the host into the server field.
I'll push a PR for this
