### ISSUE TITLE
[Bug]: Chrome breaks when changing language

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#485]
## Describe the bug:

When changing the language in the chrome header, it breaks the chrome SSI.  I'm guessing this has to do with how the paths are configured to use rh_local and init.js, or perhaps the sync is not syncing the static files for each locale?

## Steps to reproduce:

1. Go to a chromed spa: https://spaship-router-cpops-dev.ext.us-west.dc.preprod.paas.redhat.com/demo/chrome/
2. Click on the language change button in the top right and select a language other than english
3. Chrome now breaks and says "[an error occurred while processing this directive]"

## Expected behavior:

Chrome should display in the proper language

## Environment;

Dev

**Comment by kunyan** [comment]
It looks only Korean has this problem. I tested Chinese and Japanese, all works good

**Comment by kunyan** [comment]
Korean is using kr in `sync`
```
drwxr-sr-x. 6 1004340000 2034 49 Apr  7 06:52 .
drwxr-sr-x. 5 1004340000 2034 46 Apr  7 06:56 ..
drwxr-sr-x. 2 1004340000 2034 23 Apr  7 06:52 en
drwxr-sr-x. 2 1004340000 2034 23 Apr  7 06:52 ja
drwxr-sr-x. 2 1004340000 2034 23 Apr  7 06:52 kr
drwxr-sr-x. 2 1004340000 2034 23 Apr  7 06:52 zh_CN
```

**Comment by kunyan** [comment]
Fixed
