### ISSUE TITLE
[sync-service] don't cache 400+ autosync responses

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#49]
Right now autosync will cache any HTTP response.  It should be adjusted to only cache when the response is a 200.

We're using [axios](https://github.com/axios/axios) which followed redirects (up to 5 redirects in a row, by default), so we don't have to worry about handling 300s.  The response we get from axios should be a 200 if the request was successful.  If it's not, drop it and leave the existing cache in place.

**Comment by Jared-Sprague** [comment]
Ok PR is up for this
