### ISSUE TITLE
add a logging system

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#50]
We should add a logging system to enforce consistency and provide logging features.  Right now I'm liking [winston](https://github.com/winstonjs/winston/blob/master/docs/transports.md#winston-core) a lot.  Definitely open to other options though.

Checklist: 
- [x] added logging to common
- [x] added logging to sync-service
- [x] added logging to path-proxy

**Comment by kunyan** [comment]
The logger should not only output in console. but also in a file. and ti should be daily rotated

**Comment by mwcz** [comment]
I agree 109%.  Winston can log to many different targets, including console, files, and databases.  It doesn't handle log rotation (as far as I know) but there are other tools to handle that, like [logrotate](https://github.com/logrotate/logrotate).

**Comment by mwcz** [comment]
Just discovered pino https://github.com/pinojs/pino which sounds a lot like Winston, just another alternative.

**Comment by kunyan** [comment]
CPLabs team using https://github.com/baryon/tracer. it is a light and powerful logger.
could do log rotate
