### ISSUE TITLE
Enhance Manager to be Multi-Tenant

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#502]
We need to enhance the manager to work with multiple domains under a single manager.

This will involve a few things:
1. Configuring the manager with domain specific endpoints for the API and Routers
2. Enhancing the UI to let the user select which domain context they are working in, then the applications list, API Keys, and Environments tab will all be in that context.  Very similar to how PagerDuty does their teams selection.

**Comment by kunyan** [comment]
I think the story could be like this

1. When user login to SPAship. there have a namespace list

* access
* catalog
* developer
* customize -> you could added your api hosts

2. User could choose one of exists preset namespace, or add their own api servers
3. Once use selected one of namespace or use custom api server. the information will be store in `localstorage`. When user login to SPAship next time, there will use the exists info as default namespace
4. User could file ticket to ask cpops add their api hosts as a preset namespace
5. User could back to namespace list page in navigation bar whenever they want
6. the namespace list could fetch from API when we have ACL (optional)


The No.6 need we also has single API server. which is not support yet.

**Comment by npatil9** [comment]
We groomed this today and would be working on use cases to prioritize the immediate vs long term expectations.

**Comment by npatil9** [comment]
Waiting on a PR review. 

@sayak-sarkar spoke to Sumeet regarding designs and expect to schedule a call to have further discussion.

Additional Change: Setting up variables for environments.
