### ISSUE TITLE
[sync-service]  Separate autosync out of sync-service into it's own service

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#54]
The autosync process should be in it's own service since it is a completely separate concern than deploying and listing SPAs

**Comment by mwcz** [comment]
I like this.  I'm actually currently helping Tyler set up autosync for a SPA deployed in openshift, which currently has _no_ mechanism for updating chrome.  It was very easy, and likewise should be very easy to separate away from sync-service.

I did something like this:

```
npm install -S @spaship/sync-service
```

```js
const AutoSync = require("@spaship/lib/background/autosync");
const as = new AutoSync();
as.start();
```

Works like a charm.  That was a very easy way to _run_ autosync by itself.  It's still coupled to the sync-service's config file though.  I think that separating the configurations will be the only significant task.  For example, sync-service has config.js which governs how configurations are read in.  A separate autosync package will need an equivalent file.  As far as config file format, we can just extract the `autosync` property out of sync-service's config file config file, and that will become autosync's entire config file.  Might need to add a few extra properties like hostname, port, etc.

**Comment by Jared-Sprague** [comment]
Extract this out into it's own service

**Comment by mwcz** [comment]
Removed from MVP.
