### ISSUE TITLE
Add endpoint for deleting a spa

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#58]
You should be to delete a spa via the API

@Jared-Sprague, @kunyan would be looking into it as he would be working on addition and similar API endpoints.

**Comment by mwcz** [comment]
How does this fit in to "Code hardening, testing and documentation"?

**Comment by npatil9** [comment]
Closing before end of the current week :)

**Comment by mwcz** [comment]
Are you sure? ;)

**Comment by npatil9** [comment]
@mwcz we have two projects MVP and Minimum Viable Product (MVP). I have removed it from MVP project which doesn't require to be maintained. Hope this explains.

**Comment by npatil9** [comment]
Deprioritizing this issue for now to achieve the MVP. If possible @kunyan would take it.

**Comment by kunyan** [comment]
Fixed in #282
