### ISSUE TITLE
Create user guide for end users

### ISSUE THREAD

**Issue by cbredesen** [spaship/spaship#59]
Great job with the contributor guide! But I have a nice container platform at my disposal and I want to ship some SPAs. Let's have a user's guide ... pretty please? :)

**Comment by npatil9** [comment]
@mwcz recommends short video!

**Comment by npatil9** [comment]
May be an extension or additional FAQ like https://mojo.redhat.com/docs/DOC-1208676

**Comment by kunyan** [comment]
I added a tech FAQ in [FAQ](/spaship/spaship/wiki/FAQ)

**Comment by Jared-Sprague** [comment]
Like we were talking in chat this should be a guide only developers to users to use an already running instance of SPAship, not to set it up and configure a new instance.  We will make an Administrator Guide for that part.

**Comment by sayak-sarkar** [comment]
I'm working on a draft user guide here: https://docs.google.com/document/d/1sUBPn2fvMXIUDTHH5bGlD-b3qt3tX4xNYG4JqH_d1sU/edit?usp=sharing
It's still very much a work in progress.

**Comment by npatil9** [comment]
User guide - architecture - Should create a new one completely from the user expectations point of view.

**Comment by npatil9** [comment]
User guide is ready. Migration to docusaurus is pending.
