### ISSUE TITLE
[Feature]: Setup documentation on spaship.io using GH Pages.

### ISSUE THREAD

**Issue by npatil9** [spaship/spaship#616]

**Comment by sayak-sarkar** [comment]
I just finished doing the following:- 
1. Setup the GH pages repo at: [spaship.github.io](https://github.com/spaship/spaship.github.io) 
2. Migrated the [docusaurus](https://github.com/spaship/spaship/tree/master/docusaurus) directory to it with existing git history.
3. Setup the CNAME for [spaship.io](spaship.io)

Reassigning this issue to @Jared-Sprague for:
- [ ] Setting up the DNS, and
- [ ] Enabling HTTPS for the site.

**Comment by Jared-Sprague** [comment]
Ok DNS update is done!

**Comment by Jared-Sprague** [comment]
I don't think we really need https right now since this is anonymous and static
