### ISSUE TITLE
Create interface for authorization points in the platform

### ISSUE THREAD

**Issue by Jared-Sprague** [spaship/spaship#62]
A generic interface for authorizing specific actions in spaship, such as deploying a spa etc.  This can be plugged in with specific implementations, for example rover groups.

**Comment by npatil9** [comment]
@mwcz have we started working on this?

**Comment by npatil9** [comment]
@mwcz @Jared-Sprague do we still want this issue to be part of MVP? We have very minimal time to work and achieve this.
