### ISSUE TITLE
Consider TypeScript

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#73]
Opening this issue to have a discussion about TypeScript and whether SPAship should be 100% TS.  I recall @kunyan and @sayak-sarkar both bringing up TS in past discussions.

The question to answer here is: Should we be writing this tool in TypeScript?

For fun, I've been converting a [very old side-project](https://github.com/mwcz/median-cut-js) to TS and it's been quite nice.  I mostly write vanilla JS though, so it would be a bit of a learning curve for me.

In addition to all the typical pros and cons of TypeScript, here are some additional project-specific points to consider:

 - spa-manager is already in TS
 - sync-service, common, path-proxy, and the cli are already written in vanilla JS
 - if we switch, _now_ is the best possible time
 - the cli framework ([oclif](https://oclif.io/docs/introduction.html)) is nicer to work with in typescript
 - some devs (me for instance) are not TS experts

What does everyone think?  @Jared-Sprague @kunyan @sayak-sarkar @npatil9

**Comment by kunyan** [comment]
IMO

**Good**

- ES(x) support. no matter ES5, ES2015, ES201X, Developer could ignore it and use any new feature they want
- Easy compile to any target: ES5, ES6 and other
- Compile error to avoid runtime error
- Type autocomplete. more easy to do coding
- Syntactic sugar。 Less code do more thing

**Bad**
- Many @type definition files in devDependency
- Some 3rd party package not have definition file. like [openshift-rest-client](https://github.com/nodeshift/openshift-rest-client)
- Code should compile first, can not run it directly
- It won't help a lot for small/light project. and will increase bundle size.





However, more and more repo are using TypeScript to rewrite all codes
and TypeScript also becoming to a [de facto standard](https://en.wikipedia.org/wiki/De_facto_standard) for JS community

I had use TypeScript for 2 years. but the more you dabble in, the less you grasp :)

**Comment by sayak-sarkar** [comment]
@kunyan has already nicely summarized most of what I am also thinking in this context. So I'll simply say that I'm quite in favor of moving to Typescript. 

Also, all things said, I think the biggest advantage that this would provide is in terms of uniformity  of code in terms of language as well as coding practices.

**Comment by mwcz** [comment]
Cool.  I do think the decision should be unanimous.

I think this is a good summary of our current positions.  Please correct me if I've mis-stated your opinion!

- @sayak-sarkar in favor of moving to TS
- @Jared-Sprague unknown
- @kunyan sees pros and cons, no firm opinion
- @mwcz sees pros and cons, no firm opinion

**Comment by mwcz** [comment]
I'm going to close this.  I don't think we'll be switching to TS.
