### ISSUE TITLE
rename path-proxy, sync-service, and spa-manager

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#74]
Rename a few packages to make things clearer.

`sync-service` &rarr; `api`

- [x] rename npm `@spaship/sync-service` package to `@spaship/api`
- [x] rename repo directory: `/packages/sync-service` to `/packages/api`
- [x] bulk rename all `sync-service` references within the repo to `api`

`spa-manager` &rarr; `manager`

- [x] rename npm `@spaship/spa-manager` package to `@spaship/manager`
- [x] rename repo directory: `/packages/spa-manager` to `/packages/manager`
- [x] bulk rename all `spa-manager` references within the repo to `manager`

`path-proxy` &rarr; `router`

- [x] rename npm `@spaship/path-proxy` package to `@spaship/router`
- [x] rename repo directory: `/packages/path-proxy` to `/packages/router`
- [x] bulk rename all `path-proxy` references within the repo to `router`

other tasks

- [x] rename github labels
- [ ] publish new packages to npm
- [ ] npm deprecate old packages, leave a message about the new package names

**Comment by npatil9** [comment]
@mwcz are you working it?

**Comment by Jared-Sprague** [comment]
This doesn't need to wait for auto-sync to be extracted to rename
