### ISSUE TITLE
[Bug]: redirect loop in local development

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#767]
## Describe the bug:

In a local development environment, running on `localhost:2468`, attempting to log in results in a redirect loop.

## Steps to reproduce:

 1. Start the API and manager locally
 2. attempt to log in to the manager

## Expected behavior:

Log-in successful.

## Screenshots:

I'll take some and add them.

## Environment;

- Operating System(s): Fedora 32
- Browser: Chrome 85

## Additional context

From stepping through the auth code in the debugger, the login does seem to be successful.  There is a point where the access & refresh tokens exist and everything looks good.  Then, a moment later they're gone.  My best guess is that there are two instances of Keycloak, instantiated in different parts of the manager, one which succeeded in initializing and one which failed.  I've suspected this for a while while working on #629.  I think there's a good chance that fixing one of these bugs will fix them both.

**Comment by mwcz** [comment]
@kunyan @sayak-sarkar Have either of you seen this bug?

**Comment by sayak-sarkar** [comment]
Nope. I just saw this. I'll try to reproduce this in the morning and get back here.

**Comment by sayak-sarkar** [comment]
@mwcz I tried reproducing and faced the same issue. It seems the auth process is completing successfully but then again getting called from somewhere. Still trying to figure out where the other call is coming from.

**Comment by mwcz** [comment]
Investigating some more.  Keycloak.js's onAuthLogout handler is running exactly 5 seconds after each successful login.  I no longer think keycloak is being initialized twice, it now looks like there's a succesful login followed by a predictible logout 5 seconds later.

I'll check with the keycloak admins to see if there's anything in the client's config that could cause that.

**Comment by mwcz** [comment]
More observations:

The delay before logout is 5 seconds because that's the default interval for checking the keycloak iframe for its status.  After 5 seconds, the iframe is consulted "am I logged in?" and it says no, which triggers the logout.

Why is the iframe saying no?  My hunch is it's related to SameSite cookies.  Many of the cookies keycloak writes do not have the SameSite flag (in upstream they do, but not in the Red Hat SSO version we are pointing to).  This also explains why this untouched code began misbehaving.  Without access to those cookies, the iframe can't accurately verify auth status.

Path forward?  Upgrade Keycloak/RHSSO.  Or, as a short-term solution, adding a new entry to the kc client's allowedOrigins which shares a TLD with the one the cookies are scoped to, could help.

**Comment by mwcz** [comment]
A workaround for fixing the local development redirect loop.

Note which domain or subdomain keycloak scopes its cookies to (ex: `.foo.com`).  Now create an entry in your `/etc/hosts` for a subdomain of that, such as `127.0.0.1 spaship.foo.com`.  Then, when you view SPAship manager in browser, visit `spaship.foo.com:2468` (or alternate port, if specified).

I'll distribute instructions internally for how to do this for our particular keycloak instance.

**Comment by mwcz** [comment]
Oh and to close the loop on #629, it seems _very_ likely that the two bugs are unrelated after all.
