### ISSUE TITLE
Add "report issue" button to Manager

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#892]
Add a button to the manager that links to the Create Issue page on github.

**Comment by kunyan** [comment]
We can use https://support.atlassian.com/jira-cloud-administration/docs/use-the-issue-collector/

**Comment by kunyan** [comment]
I just made a test on localhost
![2020-11-06 20-19-50 2020-11-06 20_21_36](https://user-images.githubusercontent.com/752130/98365664-b3808300-206d-11eb-9ee5-2401783fa1b9.gif)

**Comment by kunyan** [comment]
The JIRA issue collector  provide 2 way to embed

1. Embedding in HTML
2. Embedding in scripts

I'll do a few code change to adapt it without big changes. will send a PR later

**Comment by mwcz** [comment]
I commented on the PR but I'll leave a comment here too.   I like the idea of reporting to JIRA for the internal SPAship instances.  It makes sense, since a lot of feedback will be about those instances (ex: a SPAship API is misconfigured and not working; that doesn't need to go to github).  If there are issues that should go to github, we can copy them over ourselves.

My only request is that this be configurable, since not all SPAship instances will want to be integrated with JIRA, and those that are will want to report issues to different JIRA projects.

**Comment by kunyan** [comment]
@mwcz 

Answer the questions here

> I have a couple of questions:
> 1. Do we really have to pull in jQuery for this?
> 2. How can we make this configurable? Not all SPAship instances will be linked to JIRA, and those that are won't all be linked to the same JIRA project(s).



1. Yes, I just made config code change, there are no change in SPAship code.

```
(function () {
    const head = document.getElementsByTagName("head")[0];
    const script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://this-is-jira-issue-collctoer-link/asdasasdasdas
    document.getElementsByTagName("head")[0].appendChild(script);
})();

function showReportButton() {
    const reportButton = document.getElementById("atlwdg-trigger");
    if (reportButton) {
      reportButton.style.zIndex=999;
    }
}

setTimeout(showReportButton, 2000)
```


2. This is setup on SPAship manager. not on the user instances.
I put the top codes into `config/manager.js`.

**Comment by mwcz** [comment]
Sounds good!
