### ISSUE TITLE
fix JWT auth

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#969]
#913 affected the logic that determines whether an incoming request is using JWT or API key auth.  The result is that JWT requests are always treated as if they are API key requests, and so they fail with "Invalid API key".

This is a big blocker because it makes the manager unusable.

@kunyan @sayak-sarkar When writing and reviewing #913, did either of you test out the manager?

**Comment by sayak-sarkar** [comment]
Indeed I did not check this on the manager. On hindsight, I probably should have! Nice catch @mwcz!

**Comment by mwcz** [comment]
I didn't catch it exactly, more like it caught me. :sweat_smile:
